#include <stdio.h>
#include <stdlib.h>
#include <locale.h>
#include <string.h>
#include "bbl.h"

int main()
{
  int codigo, opcao;
  ListaDeTarefas list;
  Informacoes inf;
  Data hoje;
  criarListas(&list);
  printf("====================================\n");
  printf("====         ===       =====    ====\n");
  printf("=======   ======  ==========    ====\n");
  printf("=======   ======       =====    ====\n");
  printf("=======   ===========  =====    ====\n");
  printf("=======   ======       =====    ====\n");
  printf("====================================\n");
  printf("=========Inserir data atual=========\n");
  printf("====================================\n");
  printf("=      Insira o hora (1 a 23):     =\n");
  printf("====================================\n");
  scanf("%i", &hoje.hora);
  system("cls");
  printf("====================================\n");
  printf("====         ===       =====    ====\n");
  printf("=======   ======  ==========    ====\n");
  printf("=======   ======       =====    ====\n");
  printf("=======   ===========  =====    ====\n");
  printf("=======   ======       =====    ====\n");
  printf("====================================\n");
  printf("=========Inserir data atual=========\n");
  printf("====================================\n");
  printf("=      Insira o dia (1 a 30):      =\n");
  printf("====================================\n");
  scanf("%i", &hoje.dia);
  system("cls");
  printf("====================================\n");
  printf("====         ===       =====    ====\n");
  printf("=======   ======  ==========    ====\n");
  printf("=======   ======       =====    ====\n");
  printf("=======   ===========  =====    ====\n");
  printf("=======   ======       =====    ====\n");
  printf("====================================\n");
  printf("=========Inserir data atual=========\n");
  printf("====================================\n");
  printf("=      Insira o mes (1 a 12):      =\n");
  printf("====================================\n");
  scanf("%i", &hoje.mes);
  system("cls");
  printf("====================================\n");
  printf("====         ===       =====    ====\n");
  printf("=======   ======  ==========    ====\n");
  printf("=======   ======       =====    ====\n");
  printf("=======   ===========  =====    ====\n");
  printf("=======   ======       =====    ====\n");
  printf("====================================\n");
  printf("=========Inserir data atual=========\n");
  printf("====================================\n");
  printf("=     Insira o ano (2023 a ?):     =\n");
  printf("====================================\n");
  scanf("%i", &hoje.ano);
  do
  {
    system("cls");
    printf("====================================\n");
    printf("====         ===       =====    ====\n");
    printf("=======   ======  ==========    ====\n");
    printf("=======   ======       =====    ====\n");
    printf("=======   ===========  =====    ====\n");
    printf("=======   ======       =====    ====\n");
    printf("====================================\n");
    printf("========== Menu Principal ==========\n");
    printf("====================================\n");
    printf("=1. Inserir  tarefa  na  lista     =\n");
    printf("=2. Remover  tarefa  da  lista     =\n");
    printf("=3. Exibir   tarefas por ordem     =\n");
    printf("=4. Exibir   tarefas por codigo    =\n");
    printf("=5. Salvar   lista   de  tarefas   =\n");
    printf("=6. Importar lista   de  tarefas   =\n");
    printf("=7. Finalizar programa             =\n");
    printf("====================================\n");
    printf("=Insira  a  opcao  desejada  abaixo=\n");
    printf("====================================\n");
    scanf("%d", &opcao);
    system("cls");
    while (opcao < 0 || opcao > 7)
    {
      system("cls");
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("========== Menu Principal ==========\n");
      printf("====================================\n");
      printf("=1. Inserir  tarefa  na  lista     =\n");
      printf("=2. Remover  tarefa  da  lista     =\n");
      printf("=3. Exibir   tarefas por ordem     =\n");
      printf("=4. Exibir   tarefas por codigo    =\n");
      printf("=5. Salvar   lista   de  tarefas   =\n");
      printf("=6. Importar lista   de  tarefas   =\n");
      printf("=7. Finalizar programa             =\n");
      printf("====================================\n");
      printf("=Insira  a  opcao  desejada  abaixo=\n");
      printf("====================================\n");
      printf("= Opcao invalida tente novamente!  =\n");
      printf("====================================\n");
      scanf("%d", &opcao);
      system("cls");
    }
    switch (opcao)
    {
    case 1:
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("============== Inserir =============\n");
      printf("====================================\n");
      printf("= Prioridade 1  ====  Prioridade 2 =\n");
      printf("= Prioridade 3  ====  Prioridade 4 =\n");
      printf("====================================\n");
      printf("= 1)             == 2)             =\n");
      printf("=   Importante   ==   Importante   =\n");
      printf("=       e        ==      mas       =\n");
      printf("=    Urgente     ==   Nao urgente  =\n");
      printf("=                ==                =\n");
      printf("====================================\n");
      printf("====================================\n");
      printf("= 3)             == 4)             =\n");
      printf("=    Urgente     == Nao importante =\n");
      printf("=      mas       ==       e        =\n");
      printf("= Nao importante ==   Nao urgente  =\n");
      printf("=                ==                =\n");
      printf("====================================\n");
      printf("=  Insira a opcao desejada abaixo: =\n");
      printf("====================================\n");
      scanf("%d", &inf.Prio);
      system("cls");
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("============== Inserir =============\n");
      printf("====================================\n");
      printf("=     Digite o nome da tarefa:     =\n");
      printf("====================================\n");
      scanf("%50s", inf.nome);
      system("cls");
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("============== Inserir =============\n");
      printf("====================================\n");
      printf("=    Digite o codigo da tarefa:    =\n");
      printf("====================================\n");
      scanf("%i", &inf.codTaf);
      system("cls");
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("====== Inserir hora da tarefa ======\n");
      printf("====================================\n");
      printf("= Insira a hora da tarefa(1 a 23): =\n");
      printf("====================================\n");
      scanf("%i", &inf.dat.hora);
      system("cls");
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("====== Inserir data da tarefa ======\n");
      printf("====================================\n");
      printf("=      Insira o dia (1 a 30):      =\n");
      printf("====================================\n");
      scanf("%i", &inf.dat.dia);
      system("cls");
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("====== Inserir data da tarefa ======\n");
      printf("====================================\n");
      printf("=      Insira o mes (1 a 12):      =\n");
      printf("====================================\n");
      scanf("%i", &inf.dat.mes);
      system("cls");
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("====== Inserir data da tarefa ======\n");
      printf("====================================\n");
      printf("=     Insira o ano (2023 a ?):     =\n");
      printf("====================================\n");
      scanf("%i", &inf.dat.ano);
      system("cls");
      adicionarTarefa(&list, hoje, inf);
      break;

    case 2:
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("============== Remover =============\n");
      printf("====================================\n");
      printf("= Digite o código da tarefa a ser  =\n");
      printf("= removida:                        =\n");
      printf("====================================\n");
      scanf("%d", &codigo);
      system("cls");
      removerTarefa(&list, &inf, codigo);
      break;

    case 3:
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("========== Exibir por ordem ========\n");
      printf("====================================\n");
      system("pause");
      system("cls");
      exibirTarefasPorOrdem(&list);
      break;

    case 4:
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("======== Exibir por código =========\n");
      printf("====================================\n");
      printf("= Digite o codigo da tarefa a ser  =\n");
      printf("= exibida:                         =\n");
      printf("====================================\n");
      scanf("%d", &codigo);
      system("cls");
      exibirTarefaPorCodigo(list, codigo);
      printf("xxxx");
      break;

    case 5:
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("============== Salvar ==============\n");
      printf("====================================\n");
      salvaLista(&list);
      break;

    case 6:
      printf("====================================\n");
      printf("====         ===       =====    ====\n");
      printf("=======   ======  ==========    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("=======   ===========  =====    ====\n");
      printf("=======   ======       =====    ====\n");
      printf("====================================\n");
      printf("============= Importar =============\n");
      printf("====================================\n");
      carregaLista(&list, hoje);
      break;
    }
  } while (opcao != 7);
  return 0;
}
